---
title: "ASDpreterm_Genitic_part_Rare_variant_burden"
Authors: "Yali Zhang"
Correspondence: "Dr. Kristiina Tammimies, kristiina.tammimies@ki.se"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for performing the rare variants burden analysis in genetic analysis in ASD-preterm project.\
Here show the analysis code for the DNV identified in ES from Zhou et.al,. paper.\
For the DNV identified in GE, same codes with correponding input data were used.

### Rare variants burden
```{r, message=F, warning=F}
library(patchwork)
library(ggsignif)
library(ggplot2)
library(geepack)

BMS_V9 <- read.csv("../phenotype_dataset/SPARK_collection_v9_2022-12-12/basic_medical_screening_2022-12-12.csv",header = T)
BMS_V9_ASD <- BMS_V9[BMS_V9$asd=="True",]
BMS_V9_ASD[is.na(BMS_V9_ASD$birth_prem),'birth_prem'] <- 0

asd_cohort_ind <- as.data.frame(read_excel('../Data/ASD_Discov_Trios_SPARK_SPID.xlsx',sheet = 1, na = 'NA', col_names = F))
DNV_f <- as.data.frame(read_excel('../Data/41588_2022_1148_MOESM5_ESM.xlsx',sheet = 1, na = 'NA'))

# LOF
high_effect <- c("frameshift","splice_acceptor","splice_donor","start_lost","stop_gained","stop_lost")
DNV_f_SPARK <- DNV_f %>% filter(Cohort == "SPARK") # 13755
DNV_f_SPARK_LOF <- DNV_f_SPARK[str_detect(DNV_f_SPARK$GeneEff, paste(high_effect, collapse = "|")),] # 1451

# NDD gene
NDD_gene_list <- read.csv('../../NDD gene list/240314/NDD_gene_filter_240314.csv')
DNV_f_SPARK_NDDgene_index <- c()
for (i in 1:length(DNV_f_SPARK$IID)){
  geneid <- strsplit(DNV_f_SPARK$GeneID[i],';')[[1]]
  hgnc <- strsplit(DNV_f_SPARK$HGNC[i],';')[[1]]
  for (j in geneid){
    if (j %in% NDD_gene_list$ensembl_id_GRch37_final){
      DNV_f_SPARK_NDDgene_index <- c(DNV_f_SPARK_NDDgene_index,i)
    }
  }
  for (k in hgnc){
    if (k %in% NDD_gene_list$gene_symbol){
      DNV_f_SPARK_NDDgene_index <- c(DNV_f_SPARK_NDDgene_index,i)
    }
  }
}
DNV_f_SPARK_NDDgene_index <- unique(DNV_f_SPARK_NDDgene_index)
DNV_f_SPARK_NDDgene <- DNV_f_SPARK[DNV_f_SPARK_NDDgene_index,]

DNV_f_SPARK_LOF_NDDgene_index <- c()
for (i in 1:length(DNV_f_SPARK_LOF$IID)){
  geneid <- strsplit(DNV_f_SPARK_LOF$GeneID[i],';')[[1]]
  hgnc <- strsplit(DNV_f_SPARK_LOF$HGNC[i],';')[[1]]
  for (j in geneid){
    if (j %in% NDD_gene_list$ensembl_id_GRch37_final){
      DNV_f_SPARK_LOF_NDDgene_index <- c(DNV_f_SPARK_LOF_NDDgene_index,i)
    }
  }
  for (k in hgnc){
    if (k %in% NDD_gene_list$gene_symbol){
      DNV_f_SPARK_LOF_NDDgene_index <- c(DNV_f_SPARK_LOF_NDDgene_index,i)
    }
  }
}
DNV_f_SPARK_LOF_NDDgene_index <- unique(DNV_f_SPARK_LOF_NDDgene_index)
DNV_f_SPARK_LOF_NDDgene <- DNV_f_SPARK_LOF[DNV_f_SPARK_LOF_NDDgene_index,]

DNV_f_SPARK_LOF$NDD_gene[DNV_f_SPARK_LOF_NDDgene_index] <- 1
# write.csv(DNV_f_SPARK_LOF,'WES_DNV_f_SPARK_LOF.csv')


# Annotate BMC information
for (i in 1:length(asd_cohort_ind$...1)) {
  
  if (asd_cohort_ind$...1[i] %in% BMS_V9$subject_sp_id){
    asd_cohort_ind[i,'BMC'] <- 1
    
    asd_cohort_ind[i,'FID'] <- BMS_V9[BMS_V9$subject_sp_id == asd_cohort_ind$...1[i],'family_sf_id']
    asd_cohort_ind[i,'asd'] <- BMS_V9[BMS_V9$subject_sp_id == asd_cohort_ind$...1[i],'asd']
    asd_cohort_ind[i,'birth_prem'] <- BMS_V9[BMS_V9$subject_sp_id == asd_cohort_ind$...1[i],'birth_prem']
    asd_cohort_ind[i,'gest_age'] <- BMS_V9[BMS_V9$subject_sp_id == asd_cohort_ind$...1[i],'gest_age']
    asd_cohort_ind[i,'sex'] <- BMS_V9[BMS_V9$subject_sp_id == asd_cohort_ind$...1[i],'sex']
    
    if (!is.na(asd_cohort_ind$birth_prem[i])){
      asd_cohort_ind[i,'Delivery term'] <- "Preterm"
      if (is.na(asd_cohort_ind$gest_age[i])){
        asd_cohort_ind[i,'Stage'] <- 'Preterm - Unknown gestational age'
      }else{
        g_age <- as.numeric(asd_cohort_ind$gest_age[i])
        
        if (g_age < 28){
          asd_cohort_ind[i,'Stage'] <- 'Extremely preterm'
        }else if (g_age > 27 && g_age < 32) {
          asd_cohort_ind[i,'Stage'] <- 'Very preterm'
        }else if (g_age >= 32 && g_age < 34) {
          asd_cohort_ind[i,'Stage'] <- 'Moderate preterm'
        }else if(g_age >= 34 && g_age < 37){
          asd_cohort_ind[i,'Stage'] <- 'Late preterm'
        }
      }
    }else{
      asd_cohort_ind[i,'Delivery term'] <- "Term"
      asd_cohort_ind[i,'Stage'] <- "Term"
    }
    
  }else{
    asd_cohort_ind[i,'BMC'] <- 0
  }
  
  ind <- asd_cohort_ind$...1[i]
  if (ind %in% DNV_f_SPARK$IID){
    asd_cohort_ind[i,'DNV'] <- sum(DNV_f_SPARK$IID == ind)
    if (ind %in% DNV_f_SPARK_LOF$IID){
      asd_cohort_ind[i,'LOF'] <- sum(DNV_f_SPARK_LOF$IID == ind)
    }else{
      asd_cohort_ind[i,'LOF'] <- 0
    }
  }else{
    asd_cohort_ind[i,'DNV'] <- 0
    asd_cohort_ind[i,'LOF'] <- 0
  }
  
  if (ind %in% DNV_f_SPARK_NDDgene$IID){
    asd_cohort_ind[i,'DNV_NDDgene'] <- sum(DNV_f_SPARK_NDDgene$IID == ind)
    if (ind %in% DNV_f_SPARK_LOF_NDDgene$IID){
      asd_cohort_ind[i,'LOF_NDDgene'] <- sum(DNV_f_SPARK_LOF_NDDgene$IID == ind)
    }else{
      asd_cohort_ind[i,'LOF_NDDgene'] <- 0
    }
  }else{
    asd_cohort_ind[i,'DNV_NDDgene'] <- 0
    asd_cohort_ind[i,'LOF_NDDgene'] <- 0
  }
}

# write.csv(asd_cohort_ind,'asd_cohort_ind_WES_DNV.csv',row.names = F)

asd_cohort_ind_BMC <- asd_cohort_ind[which(asd_cohort_ind$BMC==1),]
asd_cohort_ind_BMC$ASD_code <- ifelse(asd_cohort_ind_BMC$asd == 'True', 1, 0)
asd_cohort_ind_BMC$prem_code <- ifelse(asd_cohort_ind_BMC$`Delivery term` == 'Preterm', 1, 0)

f_id_list <- unique(asd_cohort_ind_BMC$FID)
f_id_num <- seq(1,length(f_id_list))
for (i in 1:nrow(asd_cohort_ind_BMC)){
  asd_cohort_ind_BMC[i,'family_sf_id_code'] <- f_id_num[which(f_id_list %in% asd_cohort_ind_BMC$FID[i])]
}
asd_cohort_ind_BMC$sex <- as.factor(asd_cohort_ind_BMC$sex)
asd_cohort_ind_BMC$asd <- as.factor(asd_cohort_ind_BMC$asd)
asd_cohort_ind_BMC$asd <- factor(asd_cohort_ind_BMC$asd,levels = c('True','False'))


# GEE model - statistical significance for event rate
p.list <- c()
model1 <- geeglm(DNV ~ prem_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$ASD_code==1,], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model1)[["coefficients"]][["Pr(>|W|)"]][2])

model3 <- geeglm(DNV_NDDgene ~ prem_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$ASD_code==1,], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model3)[["coefficients"]][["Pr(>|W|)"]][2])

model2 <- geeglm(LOF ~ prem_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$ASD_code==1,], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model2)[["coefficients"]][["Pr(>|W|)"]][2])

model4 <- geeglm(LOF_NDDgene ~ prem_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$ASD_code==1,], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model4)[["coefficients"]][["Pr(>|W|)"]][2])

model5 <- geeglm(DNV ~ ASD_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$`Delivery term`=='Preterm',], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model5)[["coefficients"]][["Pr(>|W|)"]][2])

model7 <- geeglm(DNV_NDDgene ~ ASD_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$`Delivery term`=='Preterm',], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model7)[["coefficients"]][["Pr(>|W|)"]][2])

model6 <- geeglm(LOF ~ ASD_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$`Delivery term`=='Preterm',], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model6)[["coefficients"]][["Pr(>|W|)"]][2])

model8 <- geeglm(LOF_NDDgene ~ ASD_code+sex, id = family_sf_id_code, data = asd_cohort_ind_BMC[asd_cohort_ind_BMC$`Delivery term`=='Preterm',], family = poisson(), corstr = "independence") # 
p.list <- c(p.list,summary(model8)[["coefficients"]][["Pr(>|W|)"]][2])
print(p.list)

### calculate event rate of variants
event_rate_basic <- function(var1 = 'ASD',
                             cond1 = '2',
                             var2 = 'Delivery term',
                             df = PED_kid_BMC,
                             variant = 'DNV_n',
                             variant_name_revise = 'DNV'){
  var2_group1 <- unique(df[,var2])[1]
  var2_group2 <- unique(df[,var2])[2]
  
  n1 <- sum(df[,var1] == cond1 & df[,var2]== var2_group1) 
  n2 <- sum(df[,var1] == cond1 & df[,var2]== var2_group2) 
  
  r_1 <- mean(df[which(df[,var1]  == cond1 & df[,var2]  == var2_group1),variant],na.rm = T)
  r_2 <- mean(df[which(df[,var1]  == cond1 & df[,var2]  == var2_group2),variant],na.rm = T)
  
  sd_1 <- sd(df[which(df[,var1]  == cond1 & df[,var2]  == var2_group1),variant],na.rm = T) / sqrt(n1)
  sd_2 <- sd(df[which(df[,var1]  == cond1 & df[,var2]  == var2_group2),variant],na.rm = T) / sqrt(n2)
  
  df_out <- cbind.data.frame('DNV_rate' = c(r_1,r_2), 'rate_sd' = c(sd_1,sd_2) ,var2 = c(var2_group1,var2_group2), 'Variant' = c(variant_name_revise,variant_name_revise) )
  
  return(df_out)
}

## Within ASD, preterm vs term
variant_x <- c('DNV','LOF', 'DNV_NDDgene', 'LOF_NDDgene')
variant_y <- c('DNV','LOF','DNV on\nNDD gene','LOF on\nNDD gene')
DNV_rate_df2 <- data.frame()
for (i in 1:4) {
  df_x <- event_rate_basic(var1 = 'asd', # within region
                           cond1 = 'True', 
                           var2 = 'Delivery term', # compare group
                           df = asd_cohort_ind_BMC,
                           variant = variant_x[i],
                           variant_name_revise = variant_y[i])
  DNV_rate_df2 <- rbind.data.frame(DNV_rate_df2,df_x)
}

colnames(DNV_rate_df2) <- c('DNV_rate',"SE",'Delivery','Variant')
DNV_rate_df2$Variant <- factor(DNV_rate_df2$Variant,levels = c('DNV','DNV on\nNDD gene','LOF','LOF on\nNDD gene'))
###
target_lable_WESdnv <- paste0(levels(factor(DNV_rate_df2$Delivery)),' (n=',c(sum(asd_cohort_ind_BMC$`Delivery term` == 'Preterm' & asd_cohort_ind_BMC$asd=='True'),sum(asd_cohort_ind_BMC$`Delivery term` == 'Term' & asd_cohort_ind_BMC$asd=='True')),')')
p_WES_event_rate <-
  ggplot(DNV_rate_df2,aes(x=Variant,y=DNV_rate,fill=Delivery))+
  geom_bar(stat = 'identity',position=position_dodge())+
  geom_errorbar(aes(ymin = DNV_rate - SE, ymax = DNV_rate + SE),color = 'darkgrey',width = 0.1,position=position_dodge(width = 0.9)) +
  geom_text(aes(label=round(DNV_rate,2),vjust = c(-1,-1.8,-1,-1.2,-1,-1.2,-0.8,-0.8)),
            position=position_dodge(width=1),
            size=3.6)+
  theme_classic()+
  ylab('Events Rate')+
  xlab('')+
  theme(axis.title = element_text(size=12),
        axis.text = element_text(size=11),
        legend.text = element_text(size=9),
        panel.grid = element_blank(),
        legend.background = element_rect(colour = 'darkgrey'),
        legend.position = c(0.78,0.8))+
  geom_signif(annotations = c('p=0.32','p=0.43','p=0.8','p=0.73') # gee
              ,y_position = c(1.64,0.47,0.34,0.22)
              ,xmin = c(0.75,1.75,2.75,3.75)
              ,xmax = c(1.25,2.25,3.25,4.25)
              ,tip_length = 0.01
              ,color="black",textsize = 3.5)+
  scale_fill_manual(name="Delivery term of ASD",values = c('#C51D1E',"#4792C4"),
                    breaks=levels(factor(DNV_rate_df2$Delivery)),labels=c(target_lable_WESdnv))
# save(p_WES_event_rate, file = "figure_rdata/240613_WES_DNV_EventRate.rdata")

## within preterm -> asd vs non-asd
variant_x <- c('DNV','LOF', 'DNV_NDDgene', 'LOF_NDDgene')
variant_y <- c('DNV','LOF','DNV on\nNDD gene','LOF on\nNDD gene')
DNV_rate_df4 <- data.frame()
for (i in 1:4) {
  df_x <- event_rate_basic(var1 = 'Delivery term', # within region
                           cond1 = 'Preterm', 
                           var2 = 'asd', # compare group
                           df = asd_cohort_ind_BMC,
                           variant = variant_x[i],
                           variant_name_revise = variant_y[i])
  DNV_rate_df4 <- rbind.data.frame(DNV_rate_df4,df_x)
}

colnames(DNV_rate_df4) <- c('DNV_rate',"SE",'ASD','Variant')
DNV_rate_df4$Variant <- factor(DNV_rate_df2$Variant,levels = c('DNV','DNV on\nNDD gene','LOF','LOF on\nNDD gene'))
###
target_lable_WESdnv2 <- paste0(c('ASD','Non-ASD'),' (n=',c(sum(asd_cohort_ind_BMC$`Delivery term` == 'Preterm' & asd_cohort_ind_BMC$asd=='True'),sum(asd_cohort_ind_BMC$`Delivery term` == 'Preterm' & asd_cohort_ind_BMC$asd=='False')),')')
p_WES_prem_event_rate <-
  ggplot(DNV_rate_df4,aes(x=Variant,y=DNV_rate,fill=ASD))+
  geom_bar(stat = 'identity',position=position_dodge())+
  geom_errorbar(aes(ymin = DNV_rate - SE, ymax = DNV_rate + SE),color = 'darkgrey',width = 0.1,position=position_dodge(width = 0.9)) +
  geom_text(aes(label=round(DNV_rate,2),vjust = c(-1.8,-2.8,-1.3,-1.3,-1.1,-1.4,-1,-1)),
            position=position_dodge(width=1),
            size=3.6)+
theme_classic()+
  ylab('Events Rate')+
  xlab('')+
  theme(axis.title = element_text(size=12),
        axis.text = element_text(size=11),
        legend.text = element_text(size=9),
        panel.grid = element_blank(),
        legend.background = element_rect(colour = 'darkgrey'),
        legend.position = c(0.75,0.8))+
  geom_signif(annotations = c('p=0.005','p=0.024','p=0.14','p=0.018') # gee
              ,y_position = c(1.62,0.44,0.3,0.2)
              ,xmin = c(0.75,1.75,2.75,3.75)
              ,xmax = c(1.25,2.25,3.25,4.25)
              ,tip_length = 0.01
              ,color="black",textsize = 3.5)+
  scale_fill_discrete(name="ASD condition of preterm",
                      breaks=levels(factor(DNV_rate_df4$ASD)),labels=c(target_lable_WESdnv2))

p_ES_DNV <- p_WES_event_rate + p_WES_prem_event_rate
print(p_ES_DNV)
```




