---
title: "ASDpreterm_Genitic_part_Polygenic_load"
Authors: "Yali Zhang"
Correspondence: "Dr. Kristiina Tammimies, kristiina.tammimies@ki.se"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for performing the PRS analysis in genetic analysis in ASD-preterm project.

### PRS distribution
```{r, message=F, warning=F}
library(patchwork)
library(readxl)
library(dplyr)
library(ggpubr)
library(epiR)
library(epitools)
library(tidyverse)
library(ggjoy)
library(geepack)
library(coefplot)
library(ggeffects)

# PRScs_PRS_file <- read.table('2_QC/relatedness.QC.rel.id')
BMS_V9 <- read.csv("../phenotype_dataset/SPARK_collection_v9_2022-12-12/basic_medical_screening_2022-12-12.csv",header = T)

PRScs_PRS_file <- read.table('../PRS/4_PRS_result/SPARK_PRS_240402.profile',header = T)

for (i in 1:length(PRScs_PRS_file$IID)) {
  
  if (PRScs_PRS_file$IID[i] %in% BMS_V9$subject_sp_id){
    PRScs_PRS_file[i,'BMC'] <- 1
    
    PRScs_PRS_file[i,'asd'] <- BMS_V9[BMS_V9$subject_sp_id == PRScs_PRS_file$IID[i],'asd']
    PRScs_PRS_file[i,'birth_prem'] <- BMS_V9[BMS_V9$subject_sp_id == PRScs_PRS_file$IID[i],'birth_prem']
    PRScs_PRS_file[i,'gest_age'] <- BMS_V9[BMS_V9$subject_sp_id == PRScs_PRS_file$IID[i],'gest_age']
    
    if (!is.na(PRScs_PRS_file$birth_prem[i])){
      PRScs_PRS_file[i,'Delivery term'] <- "Preterm"
      if (is.na(PRScs_PRS_file$gest_age[i])){
        PRScs_PRS_file[i,'Stage'] <- 'Preterm - Unknown gestational age'
      }else{
        g_age <- as.numeric(PRScs_PRS_file$gest_age[i])
        if (g_age < 28){
          PRScs_PRS_file[i,'Stage'] <- 'Extremely preterm'
        }else if (g_age > 27 && g_age < 32) {
          PRScs_PRS_file[i,'Stage'] <- 'Very preterm'
        }else if (g_age >= 32 && g_age < 34) {
          PRScs_PRS_file[i,'Stage'] <- 'Moderate preterm'
        }else if(g_age >= 34){
          PRScs_PRS_file[i,'Stage'] <- 'Late preterm'
        }
      }
    }else{
      PRScs_PRS_file[i,'Delivery term'] <- "Term"
      PRScs_PRS_file[i,'Stage'] <- "Term"
    }
    
  }else{
    PRScs_PRS_file[i,'BMC'] <- 0
  }
}

# z-standardization of PRS
PRScs_PRS_file[,'stand_PRS'] <- scale(PRScs_PRS_file$SCORE, center = TRUE, scale = TRUE)[,1]
# normality test
# qqnorm(PRScs_PRS_file$stand_PRS)
shapiro.test(sample(PRScs_PRS_file$stand_PRS,5000))

## compare groups
# asd.preterm vs asd.term
# asd.preterm vs non-asd.preterm
# asd.term vs non-asd.term
# asd all vs non-asd all
PRScs_PRS_file$ASD[PRScs_PRS_file$asd == 'True'] <- 'ASD'
PRScs_PRS_file$ASD[PRScs_PRS_file$asd == 'False'] <- 'Non-ASD'

PRScs_PRS_file_2 <- PRScs_PRS_file[which(PRScs_PRS_file$BMC == 1),]
PRScs_PRS_file_2$Group <- paste0(PRScs_PRS_file_2$ASD,'.',PRScs_PRS_file_2$`Delivery term`)
PRScs_PRS_file_2$Group_color <- PRScs_PRS_file_2$`Delivery term`

PRScs_PRS_file_3 <- PRScs_PRS_file[which(PRScs_PRS_file$BMC == 1),]
PRScs_PRS_file_3$Group <- paste0(PRScs_PRS_file_3$ASD,'.All')
PRScs_PRS_file_3$Group_color <- 'Mixture'

PRScs_PRS_file_group <- rbind.data.frame(PRScs_PRS_file_2,PRScs_PRS_file_3)

for (i in 1:length(PRScs_PRS_file_group$FID)){
  PRScs_PRS_file_group[i,'family_sf_id'] <- BMS_V9[BMS_V9$subject_sp_id == PRScs_PRS_file_group$IID[i], 'family_sf_id']
}

PRScs_PRS_file_group$ASD_code <- ifelse(PRScs_PRS_file_group$ASD == 'ASD', 1, 0)
PRScs_PRS_file_group$prem_code <- ifelse(PRScs_PRS_file_group$`Delivery term` == 'Preterm', 1, 0)

for (i in 1:length(PRScs_PRS_file_group$IID)) {
  if (PRScs_PRS_file_group$IID[i] %in% BMS_V9$subject_sp_id){
    PRScs_PRS_file_group[i,'sex'] <- BMS_V9[BMS_V9$subject_sp_id == PRScs_PRS_file_group$IID[i],'sex']
  }
}
PRScs_PRS_file_group$family_sf_id <- as.factor(PRScs_PRS_file_group$family_sf_id)

PRScs_PRS_file_group$Group <- factor(PRScs_PRS_file_group$Group,levels = c('Non-ASD.Preterm','ASD.Preterm','ASD.Term','Non-ASD.Term','ASD.All','Non-ASD.All'))
PRScs_PRS_file_group$Group_color <- factor(PRScs_PRS_file_group$Group_color ,levels = c('Preterm','Term','Mixture'))
PRScs_PRS_file_group$`ASD condition` <- PRScs_PRS_file_group$ASD

# p_PRS_dist <- 
ggplot(PRScs_PRS_file_group,aes(x=Group,y=stand_PRS,fill=Group_color))+
  geom_jitter(aes(color=Group_color,shape=`ASD condition`),position = position_jitter(0.1),size=1,alpha=0.6)+
  geom_boxplot(alpha=1,outlier.size = 0.5,size = 0.5,width=0.1,fill='transparent',)+
  geom_violin(alpha=0.3)+
  labs(x= "",y='Standardized PRS')+
  # ylim(-3.5,6)+
  # theme(title = element_text(size=14))+
  theme_bw()+
  theme(axis.text.x = element_text(size=10))+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  theme(axis.text = element_text(colour = 'black',size = 9))+
  # theme(legend.position="none")+
  geom_signif(annotations = c('NA','NA','***','***')
              ,y_position = c(4,5,5.5,5.5)
              ,xmin = c(1.05,2.05,3.05,5.05)
              ,xmax = c(1.95,2.95,3.95,5.95)
              ,tip_length = 0.03
              ,color="black")+
  scale_x_discrete(breaks=levels(PRScs_PRS_file_group$Group),
                  labels=paste0(gsub("\\.", " ", levels(PRScs_PRS_file_group$Group)),rep(c('\n(n='),6), table(PRScs_PRS_file_group$Group),rep(')',6)))+
  scale_fill_manual(name="Delivery term",values = c('#C51D1E',"#4792C4",'white'))+
  scale_color_manual(name="Delivery term",values =c('#C51D1E',"#4792C4",'black'))+
  guides(color = "none", # Remove the color legend
         fill = guide_legend(override.aes = list(shape = NA)), # Keep the fill legend
         shape = guide_legend(override.aes = list(fill = NA)))  # Keep the shape legend
```

### PRS distribution - GEE model with ancestry PC
```{r, message=F, warning=F}
## add ancestry PCA
pca_file <- read.table('../PRS/2_QC/ancestry_check/QC2.HapMapIII_CGRCh38.pca.eigenvec')

pca_scores <- pca_file[, -c(1,2)]  # Adjust indexing if necessary

for (i in 1:length(PRScs_PRS_file_group$IID)) {
  if (PRScs_PRS_file_group$IID[i] %in% pca_file$V1){
    for (k in 1:20) {
      pc <- paste0('PC',k)
      coln <- paste0('V',k+2)
      PRScs_PRS_file_group[i,pc] <- pca_file[pca_file$V1 == PRScs_PRS_file_group$IID[i],coln]
    }
}}


model1_pca <- geeglm(ASD_code ~ stand_PRS+sex+PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, id = family_sf_id, data = PRScs_PRS_file_group[PRScs_PRS_file_group$Group %in% c('Non-ASD.Preterm','ASD.Preterm'),], family = binomial(link = "logit"))
summary(model1_pca)

model2_pca <- geeglm(prem_code ~ stand_PRS+sex+PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, id = family_sf_id, data = PRScs_PRS_file_group[PRScs_PRS_file_group$Group %in% c('ASD.Preterm','ASD.Term'),], family =  binomial(link = "logit"))
summary(model2_pca)

model3_pca <- geeglm(ASD_code ~ stand_PRS+sex+PC1+PC2+PC3+PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, id = family_sf_id, data = PRScs_PRS_file_group[PRScs_PRS_file_group$Group %in% c('ASD.Term','Non-ASD.Term'),], family = binomial(link = "logit"),corstr = "independence")
summary(model3_pca) 

model4_pca <- geeglm(ASD_code ~ stand_PRS+sex+PC1+PC2+PC3+PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, id = family_sf_id, data = PRScs_PRS_file_group[PRScs_PRS_file_group$Group %in% c('ASD.All','Non-ASD.All'),], family =  binomial(link = "logit"),corstr = "independence")
summary(model4_pca)

model6_pca <- geeglm(prem_code ~ stand_PRS+sex+PC1+PC2+PC3+PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, id = family_sf_id, data = PRScs_PRS_file_group[PRScs_PRS_file_group$Group %in% c('ASD.All','Non-ASD.All'),], family =  binomial(link = "logit"),corstr = "independence")
summary(model6_pca)
```

### GEE full model
```{r, message=F, warning=F}
SPARK_nonEU <- read.csv('../PRS/2_QC/ancestry_check/SPARK_nonEU.csv')
PRS_family_df_gee_EU <- PRScs_PRS_file_group[-which(PRScs_PRS_file_group$IID %in% SPARK_nonEU$spark_nonEU),]


PRS_family_df_gee_EU$`Delivery term` <- factor(PRS_family_df_gee_EU$`Delivery term`,levels = c('Term','Preterm'))
PRS_family_df_gee_EU$sex <- factor(PRS_family_df_gee_EU$sex,levels= c('Female','Male'))

model_asd_mix <- geeglm(ASD_code ~ sex+`Delivery term`+stand_PRS, id = family_sf_id, data = PRS_family_df_gee_EU[PRS_family_df_gee_EU$Group %in% c('ASD.All','Non-ASD.All'),], family =  binomial(link = "logit"))
summary(model_asd_mix) 

custom_labels <- c('(Intercept)','Sex\n(Male)','Delivery term\n(Preterm)','Standardized PRS')

p <- coefplot(model_asd_mix, ci.style = "errorbar", ci.width = "Std.err")
coef_plot <- 
  p + scale_y_discrete(labels = custom_labels)+
  theme_bw()

ggeffects <-
ggemmeans(model_asd_mix, terms = c("stand_PRS [all]","Delivery term","sex"),rg.limit = 15000) |>
plot(color = c("#4792C4",'#C51D1E')) +
  labs(title = 'Predicted probabilities of ASD diagnosis',
       x = "Standardized PRS",
       y = "ASD",
       caption = "geeglm model: ASD_code ~ sex + Delivery term + standardized PRS")+
  theme_bw()

model_co <- coef_plot + ggeffects
print(model_co)
```